name: Build

# Controls when the action will run.
on:
# Triggers the workflow on push or pull request events for the specified branches.
  push:
    branches:
      - ci
    paths-ignore:
    - 'docs/**'

  pull_request:
    branches:
      - master
      - ci
    paths-ignore:
    - 'docs/**'

  # Allow running this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  macOS:
    runs-on: ${{ matrix.cfg.os }}
    name: ${{ matrix.cfg.name }}
    strategy:
      matrix:
        cfg:
        -  { os: macos-latest, name: 'macOS arm', opt: '--disable-iconc CC=clang CXX=clang++' }
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure
      run: sh configure  ${{ matrix.cfg.opt }}

    - name: Make
      run: make

    - name: HtmlDoc
      run: make htmldoc

    - name: Test
      run: make Test

    - name: TestReport
      run: make -C tests Report

    - name: Summary
      run: |
        cat unicon-config.log
        cat unicon-features.log
